# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  push:
  schedule:
    - cron: "*/10 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          token: ${{ secrets.token }}
      - name: npm ci
        run: npm ci
      - name: download
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          rm -rf data
          mkdir data
          node main.js
          git add .
          git commit -m update
          git push origin master
