name: DOWNLOAD

on:
  push:
  schedule:
    - cron: "*/6 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Run
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          rm -rf data
          mkdir data
          npm ci
          node main.js
          git add .
          git commit -m update
          git push origin master
