name: DOWNLOAD

on:
  push:
  schedule:
    - cron: "*/6 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Run
        run: |
          rm -rf data
          mkdir data
          npm ci
          node main.js
          git add .
          git commit -am update
          git push origin master
