name: DOWNLOAD

on:
  push:
  schedule:
    - cron: "*/6 * * * *"

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Run
        run: |
          rm -rf data
          mkdir data
          npm ci
          node main.js
      - name: Add
        run : |
          ls data
          git status
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add .
          git commit -m update
          git push origin master
